### ISSUE TITLE
POST /api/v1/users/ : при создании пользователя в теле ответа отсутствует строка с password

### ISSUE THREAD

**Issue by Role4ka** [AcceleratorYandexPracticum/calendar#108]
**Окружение:**
- сервер http://193.107.236.224
- API Calendar v1

**Шаги:**
- Отправить запрос POST /api/v1/users/ на создание пользователя
- В теле запроса указать параметры: 
`{
  "email": "user@example.com",
  "password": "string12"
}`

**Ожидаемый результат:**
В теле ответа приходят 2 параметра: email и password
`{
  "email": "user@example.com",
  "password": "string12"
}`

**Фактический результат:**
В теле ответа приходит только email
`{
    "email": "user@example.com"
}`

**Приложения:**

Дока
![Image](https://github.com/AcceleratorYandexPracticum/calendar/assets/107004358/d6a970da-8ea3-4109-98d8-f5f44b5d04e8)

Факт
![Image](https://github.com/AcceleratorYandexPracticum/calendar/assets/107004358/32645c32-5050-4e5d-8b6c-bed9a5f0d8a4)

**Ссылка на qase.io (для тестировщиков):**

**Comment by viator3m** [comment]
И здесь исправление в документации.  Поправим :+1:

**Comment by Annsjaw** [comment]
Закрыл баг пулреквестом
