### ISSUE TITLE
POST /api/auth/create/ : при создании токена приходит код ответа 200 вместо 201

### ISSUE THREAD

**Issue by Role4ka** [AcceleratorYandexPracticum/calendar#109]
**Окружение:**
- сервер http://193.107.236.224/
- API Calendar v1

**Шаги:**
1. Отправить запрос POST /api/auth/create/ на создание токена
2. В теле запроса указать параметры:
`{ "email": "user@example.com", "password": "string12" }`

**Ожидаемый результат:**
код ответа 201

**Фактический результат:**
код ответа 200
P.S. и еще в самой доке в swagger гляньте, в теле ответа не созданные токены, а почта и пароль прописаны

**Приложения:**

Факт
![Image](https://github.com/AcceleratorYandexPracticum/calendar/assets/107004358/d5a4b106-905c-430c-9c66-17f22a33a2bd)

Дока
![Image](https://github.com/AcceleratorYandexPracticum/calendar/assets/107004358/1c66b822-f362-4807-931e-99ef3b97e494)

Ссылка на qase.io (для тестировщиков):

**Comment by viator3m** [comment]
Принял. Поправим. Ошибка в нашей документации. Согласно [документации Djoser](https://djoser.readthedocs.io/en/latest/jwt_endpoints.html#jwt-create) должен приходить 200.

**Comment by Annsjaw** [comment]
Закрыл баг пул реквестом
